#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "davis"
name = "Davis"
description.en = "Lightweight CalDAV and CardDAV server"
description.fr = "Serveur CalDAV et CardDAV léger"

version = "5.4.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://github.com/tchapi/davis"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/tchapi/davis/archive/refs/tags/v5.4.1.tar.gz"
    sha256 = "46785de23d2ed9f45bea36a967e5b9f1859cb8da5a3925ff55095e41fdbafd54"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.apt]
    packages = "postgresql, php8.4-intl, php8.4-gd, php8.4-pgsql, php8.4-ldap, php8.4-curl, php8.4-dom, php8.4-xml, php8.4-zip"

    [resources.database]
    type = "postgresql"

    [resources.composer]
    version = "2.9.5"
